apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 5
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: bashofmann/rancher-demo:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: COW_COLOR
              value: purple
