apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.60.110
    - 172.18.0.2
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: app1
